<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = '名前';
$strAddress             = '住所';
$strEmail               = 'メールアドレス';
$strTown                = '街';
$strPostcode            = '郵便番号';
$strSubscribeInfo       = 'メールマガジンを受け取るメールアドレスを入力してください。';
$strRequired            = '必須項目';
$strSubscribeTitle      = 'メールマガジンの購読';
$strSubscribeButton     = '購読する';
$strPleaseSelect        = '購読したいメールマガジンを選択してください。';
$strSubmit              = '選択したメールマガジンの購読';
$strNotAvailable        = '現在、購読できるメールマガジンはありません。';
$strEnterName           = 'お名前を入力してください';
$strEnterEmail          = 'メールアドレスを入力してください';
$strConfirmEmail        = 'メールアドレス(確認入力)';
$strInvalidHostInEmail  = 'そのドメインへのメールを送ることはできません。正しいメールアドレスを入力しているか確認してください。';
$strEnterList           = '購読したいメールマガジンを選択してください。';
$strPleaseEnter         = '入力してください：';
# ありがとうメッセージにはプレースホルダーを含めることができます。
#$strThanks              = '[FIRST NAME]さん、<br/>メールマガジンを購読いただきありがとうございます。';
$strThanks              = 'メールマガジンに購読いただきありがとうございます。';
# 登録認証のお願いメッセージにはプレースホルダーを含めることができます。
#$strEmailConfirmation   = 'メールアドレス [email] がシステムに追加されました。間もなく購読したメールマガジンについて購読確定のお願いがメールで送信されます。';
$strEmailConfirmation   = 'メールアドレスがシステムに追加されました。間もなく購読したメールマガジンについて購読確定のお願いがメールで送信されます。';
$strEmailFailed          = '購読確定のお願いのメールを送信することに失敗しました。再度、「Reload」をクリックしてください。もし、まだ失敗するようでしたら、メールアドレスは"購読解除済リスト"に追加されているかもしれません。、これは、私たちのメールマガジンシステムからメールを受け取れないことを意味しています。そのような場合、管理者までご連絡ください。';
$strUnsubscribeTitle    = 'メールマガジンの購読解除';
$strUnsubscribeDone     = 'メールマガジンの購読を解除しました。間もなく確認のメールが送信されますのでご確認ください。';
$strBack                = '戻る';
$strUnsubscribeInfo     = 'メールマガジンの購読解除';
$strContinue            = '続ける';
$strUnsubscribeSelect   = '購読解除したいメールマガジンを選択してください。';
$strAllLists            = '全てのメールマガジン';
$strNoLists             = 'None of them';
$strUnsubscribeRequestForReason = 'メールマガジンに興味がなくなったことを残念に思います。私たちのサービスを改善するために、理由を教えていただければ幸いです。';
$strUnsubscribeFinalInfo = '<br/><b>注意</b>: このページはわたしたちのメールマガジンシステムから<b>永遠</b>にメールを受け取ることを停止します。もしメールアドレスを変更したいのでしたら、または、購読したいメールマガジンを変更したいのでしたら、代わりに、<a href="[PREFERENCESURL]">あなたの選択している情報</a>を更新してください。';
$strNoListsFound        = 'このメールアドレスではメールマガジンを登録できません。';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = '選択しているメールマガジンの購読解除';
$strValuesMissing       = '次の必須項目に入力されていません。';
$strConfirmInfo         = 'メールマガジンに購読いただきありがとうございます。購読したメールマガジンは下記です。';
$strConfirmTitle        = 'PHPlist メンバーシップ設定ページ';
$strUserNotFound        = 'ユーザが見つかりません。';
$strUserAlreadyInitialised = 'パスワードは既に設定されています。';
$strConfirmFailInfo     = '購読の確定はされませんでした。受け取ったメールに記載されている完全なWEBアドレスを確かめてください。ときどき、このWEBアドレスは複数行にわかれて表示されています。';
$strPreferHTMLEmail     = 'HTMLフォーマットでメールを受け取る';
$strPreferTextEmail     = 'Textフォーマットでメールを受け取る';
$strPreferredFormat      = 'メールの優先フォーマット:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = '選択した情報の更新';
$strPreferencesInfo     = '下記の情報が正しいことを確認し、"更新"ボタンをクリックしてください。';
$strUpdatePreferences   = '更新';
$strPreferencesEmailChanged = 'メールが変更されました。新しいメールアドレスを確定するためのメールを送信しますので、メールに記載されたリンクをクリックしてください。';
$strYouAreBlacklisted = 'メールアドレスが購読解除済リストに掲載されています。いかなるメッセージもあなたには決して送信されません。 <br/>
またメールを受け取るために、管理者による手動の解除が必要です。またメールマガジンを受け取りたいことをはっきりと明言しわたしたちにコンタクトしてください。購読解除済リストからあなたをはずします。';

$strPreferencesNotificationSent = '変更箇所を記載したメールを受け取ります。';
$strPreferencesUpdated = 'ありがとうございます。情報を更新しました。';
$strClickHere          = 'ここをクリック';
$strThisLink           = 'このリンク';
$strToUnsubscribe      = 'もし、いかなるメールマガジンも受け取りたくないならば、こちらをクリック：';
$strToUpdate           = '設定を更新したり購読解除する場合はこちらをクリック：';
$strSendHTML           = 'HTMLメールを受信する';
$strYes                = 'はい';
$strNo                 = 'いいえ';
$strUnsubscribe        = '登録解除';
$strAllMailinglists    = 'すべてのメールマガジン';
$strAttachmentIntro     = 'このメッセージにはウェブブラウザでみることができる添付ファイルを含まれています:';
$strLocation           = 'ロケーション';
$strFrequency           = 'メッセージを送る頻度';
$strHourly             = '毎時';
$strDaily               = '毎日';
$strWeekly             = '毎週';
$strMonthly             = '毎月';
$strChoosePassword      = 'パスワードを選択してください';
$strConfirmPassword    = 'パスワード（確認）';
$strEnterPassword       = 'パスワードを入力してください';
$strForgotPassword     = 'パスワードを忘れた方へ';
$strPassword           = 'パスワード';
$strPassword2           = 'パスワード（確認）';
$strPasswordsNoMatch    = 'パスワードが同じでありません。';
$strEmailsNoMatch     = '入力したメールアドレスがマッチしません。';
$strInvalidPassword     = 'エラー: メールアドレスまたはパスワードが妥当でありません。';
$strPasswordSent        = 'パスワードをメールで送りましたので、数分後にメールを確認してください。';
$strPasswordRemindSubject = 'このメールマガジンのパスワード';
$strPasswordRemindMessage = 'Your password is ';
$strPasswordRemindInfo = 'メールでパスワードを受け取るために、メールアドレスを入力して、"'.$strForgotPassword.'" ボタンをクリックしてください。';
$strLogin               = 'ログイン';
$strLoginTitle          = 'メールアドレスとパスワードを入力してください。';
$strLoginInfo           = 'このページはパスワードが必要です。メールアドレスとパスワードを入力してください。';
$strPersonalLocationInfo = '
  <p>このページは、メールマガジン購読者の区別を必要としています。このメールマガジン購読者の区別には、ロケーションをクリックすることが必要で、あなたに送信される各メッセージに記載されています。<br/>
  もしこのロケーションをクリックし、エラーが出るならば。ブラウザのロケーションボックス内に完全な行を確実にペーストしてください。ときどきロケーションが複数行にわたっています。</p>
  <p>もしロケーションを知らない場合、ロケーションを知らせるメールをリクエストすることができます。
  ボックスにメールアドレスを入力して、"続ける"をクリックしてください。
';
$strPersonalLocationSent = '<h1>成功しました。まもなくあなたのパーソナルロケーションが記載されたメッセージを受信します。</h1>';
$strUserExists   = '<br/>このメールアドレスをもつユーザは既に存在し、異なったパスワードになっています。';
$strUserExistsExplanationStart = '<br/>パスワードを入手するために、クリック ';
$strUserExistsExplanationLink = 'ここ';
$strUserExistsExplanationEnd = ' パーソナルロケーションをリクエストできるページにいく';
$strExplainBlacklist = 'The email that you enter here will be recorded in our database with the sole purpose of blocking any email sent from this system.';
$strForwardTitle = 'メッセージを誰かに転送する';
$strForwardSubtitle = 'メールタイトル付でメッセージを転送する ';
$strForwardEnterEmail = '転送するために妥当なメールアドレスを入力してください。';
$strForwardInvalidEmail = '%s is not a valid email address';
$strForwardBlacklistedEmail = 'Recipient has requested not to receive emails from this system.';
$strForwardEnterEmails = 'Please enter a maximum of %s valid email addresses to forward to in this box, one per line';
$strForwardPersonalNote = 'You can enter a plain text message (of maximum %d characters) that will be prepended to the forwarded mail';
$strForwardSuccessInfo ='メッセージは転送されました。';
$strForwardFailInfo = 'メッセージの転送は失敗しました。';
$strForwardAlreadyDone = 'このメッセージは既にそのメールアドレスに転送されました。';
$strForwardCountReached = 'Maximum amount of forwards reached';
$strForwardNoteLimitReached = 'Maximum length of personal note reached';
$strForwardFooter = 'このメッセージは[FORWARDEDBY]により転送されました。
  このメールマガジンは自動的に登録されません。
  このメールマガジンを購読するには以下のアドレスをクリックしてください。';
$strForward = '転送';
$strFwd = 'Fwd'; # short version of forward for email subject
